---
title: "SESAM3 sensitivity analysis"
output: html_notebook
---

Analysis of SOM stock change with FACE.

## Comparison using the FACE scenario
```{r, echo=FALSE, results='hide', message=FALSE}
library(ggplot2)
library(grid)   #unit
library(reshape)  # melt
library(RColorBrewer) # brewer.pal
library(tidyr)
library(dplyr)

myColors <- brewer.pal(5,"Dark2")	
.simpleCap <- function(s) {
    paste(toupper(substring(s, 1, 1)), substring(s, 2),  sep = "")
}
colScale <- scale_colour_manual(name = "Variant",values = myColors)
.treatments <- structure(c(1,0.5), names = c("Litter input pulse","No Litter input"))
sizeScale <- scale_size_manual(name = "Treatment",values = .treatments)

themeDefault <- theme_classic()  
```

### Setup parameters and drivers
Mass units are $gC/m^2$ or $gN/m^2$. Time unit is $yr$.
```{r}
require(sesam, quietly = TRUE)

parmsModel <- list(
  cnB = 11
  ,cnE = 3.1     # Sterner02: Protein (Fig. 2.2.), high N investment (low P) need 
    # to have low C/N for CO2 increase scenario
  ,kmN = 0.05*60     ##<< /yr enzyme turnover 60 times a year, each 6 days -> fast 
    # priming pulses
  ,kNB = 0.8     ##<< amount of recycling enzyme turnover by biomass (
    # added to assimilable, i.e. uptake instead of R)
  #,kR = 1/(10)        ##<< 1/(x years) # to demonstrate changes on short time scale
  ,kR = 1/(20)        ##<< 1/(x years) # to demonstrate changes on short time scale
  ,kL = 5           ##<< 1/(x years)   # formerly 1 year
  ,aE = 0.001*365   ##<< C biomass allocated to enzymes 1/day /microbial biomass
  ,m = 0.005*365    ##<< maintenance respiration rate   1/day /microbial biomass, 
  ## Bogedom Fig. 1
  ,tau = 1/60*365  ##<< biomass turnover rate (12 days)
  ,eps = 0.5      ##<< carbon use efficiency for growth respiration
  #,epsTvr = 0.3   ##<< carbon use efficiency of microbial tvr (part by predators 
  ,epsTvr = 0.45   ##<< carbon use efficiency of microbial tvr (part by predators 
  ## which respire and corresponding amount of N must be mineralized)
  #,iB = 0.38 * 10.57 #0.0110068*365   ##<< potential immobilization flux rate 
  ,iB = 0.4 ##<< potential immobilization flux rate 
  ## (immoPot = iB I)
  ,l = 0.96       #0.00262647*365     ##<< leaching rate of mineralN l I
  ,nu = 0.9     # microbial N use efficiency accounting for apparent 
  ## minceralization of N during uptake in heterogeneous soils
  , isEnzymeMassFlux = TRUE  ##<< compute enzyme mass fluxes
  ,kIPlant = 10.57 #0.0289652*365          ##<< plant uptake iP I
)
drivers <- list(
  iR = 0          ##<< input of residue litter
  ,iL = 300       ##<< g/m2 input per year (half NPP)
  ,cnIR = 7       ##<< C/N ratio of the residue litter input
  ,cnIL = 30      ##<< C/N ratio of the labile litter input: 
  ## N poor substrate, here no inorganic N supply, 
  ,plantNUp = 0   ##<< pland uptake of organic N
  ## currently as absolute flux
  ,iI = 0         ##<< input of mineral N
)
parms0 <- within( c(parmsModel, drivers), {
  kIPlant <- 0
  plantNUpAbs <- iL/cnIL
})
#
x0 <- x0Explicit <- c( #aE = 0.001*365
        B = 17                     ##<< microbial biomass 
        ,R = 1100                ##<< N rich substrate
        ,RN = 1100/parms0$cnIR   ##<< N rich substrate N pool
        ,L = 100                 ##<< N poor substrate
        ,LN = 100/parms0$cnIL    ##<< N poor substrate N pool
        ,I =  2                ##<< inorganic pool gN/m2
        , alpha = 0.5            ##<< microbial community partitioning [0,1]
)
#x0B <- x0SteadyA[setdiff(names(x0),"B")]
scen <- list(x0 = x0, mod = derivSesam3a, parms = parms0)
```

```{r}
runFaceSimulation <- function(
  scen, t1S =0, t2I = 50, t3S = 50
){
  # spinup to steady state
  times <- seq(0,500, length.out = 2)
  #setwd("../..");loadPkg()
  . <- scen
  res <- res1 <- as.data.frame(lsoda( .$x0, times, .$mod, parms = .$parms))
  xE <- unlist(tail(res,1))
  #xE["I"] <- 0.04  # decrease I pool # does not help filled up by mircobial tvr
  #
  # t1S years of steady state recorded
  # res <- res1S <- as.data.frame(lsoda( 
  #   xE[1:length(.$x0) + 1], 1:t1S, .$mod, parms = .$parms))
  #
  # t2I years of increased input
  fInputInc = 1.2
  parmsC2 <- within(.$parms, {# more C in litter, but not more N 
    iL <- iL*fInputInc
    cnIL <- cnIL*fInputInc
  }) 
  #times <- seq(0,t2I, length.out = t2I*6 + 1)# record bymonthly
  #times <- seq(0,t2I, length.out = 2)# only interested in end state
  times <- seq(0,t2I, length.out = round(t2I))# each year
  res <- res2I <- as.data.frame(lsoda( 
    xE[1:length(.$x0) + 1], times, .$mod, parms = parmsC2))
  res2I$time <- res2I$time + t1S 
  xE2 <- unlist(tail(res2I,1))
  #
  # t3S years of initial input
  # times <- seq(0,t3S, length.out = t3S*6 + 1) # record bymonthly
  # res <- res3S <- as.data.frame(lsoda( 
  #   xE2[1:length(.$x0) + 1], times, .$mod, parms = .$parms))
  # res3S$time <- res3S$time + t1S + t2I
  # xE3 <- tail(res3S,1)
  # resc <- rbind( res2I, res3S[-1,])
  resc <- res2I
  resc$scen <- scen$scenario
  resc
}
```

```{r eval=FALSE, include=FALSE}
resc <- runFaceSimulation(scen)
plot(R ~ time, resc, type = "l")
```

## setup distribution of parameters
```{r}
library(blockdemac)

```


## get design matrix with sobolXXX

## compute and store complete model outputs

## tell the sensitivity object

## compute scalar sensitivity measure

## Inspect outputs

