---
title: "SESAM Soil enzyme steady allocoation model in matrix form"
output: html_notebook
---

## General model
Sierra and Müller 2015 proposed a general framework of SOM models (eq. 19).

$$
\frac{dC}{dt} = IN(t) + T(C,t) N(C,t) C 
$$
where $T$ are transfer coefficients, and $N$ are instant decomposition rates.

With constant inputs, its an autonomous nonlinear model.
$$
\frac{dC}{dt} = IN + T(C) k(C) C 
$$
with $\operatorname{diag}(T(C)) = -1$.

SESAM not only models Carbon, but also Nitrogen fluxes and community composition
$\alpha$. While the subvector of Carbon pools is compartmental, and the subvector
of Nitrogen pools is compartmental, $\alpha$ is a pool not connected any other pool
and has no mass balance constraint.

## Carbon compartment
### State variables
$$
(L, R, B)
$$

### Inputs
Here labile organic pool.
$$
i_{L}(t)
$$

### Outfluxes of pools 
Components of the $k$ vector are expressed per respective pool,
Hence, they need to be multiplied by the respective pools to give the flux:

$$
\begin{align}
\operatorname{out}_L &= \operatorname{dec}_L B 
\\
\operatorname{out}_R &= \operatorname{dec}_R B 
\\
\operatorname{out}_B &= \tau +m +m_E +r_G +r_O
\end{align}
$$
where $\tau$ is microbial turnover rate, $m$ is maintenance rate, 
$m_E$ is net enzyme investment defined below, and $r_G$ and $r_O$
are growth and overflow repsiration defined below.

$$
\begin{align}
\operatorname{dec}_L &= k_L l_L 
\\
\operatorname{dec}_R &= k_R l_R 
\\
l_L = f(B, \alpha, a_E, k_{mN}) &= \frac{(1-\alpha) a_E}{k_{mN} + (1-\alpha) a_E B}
\\
l_R = f(B, \alpha, a_E, k_{mN}) &= \frac{\alpha a_E}{k_{mN} + \alpha a_E B}
\end{align}
$$

$lN$ are  enzyme limitation of decomposition devided by $B$.
$\alpha$ is community enzyme allocation, 
$a_E$ is the fraction of microbial biomass invested into synthesis of
new enzymes.
$k_{mN}$ is a lumped parameter of enzyme half-saturation in depolimerisation
and enzyme turnover.

Since DOM and enzymes are assumed to be in steady state, part of the 
enzime investment = enzyme turnover is re-uptaken by from DOM:
$$
m_E = f(a_E, \epsilon, \kappa_E) = a_E (1/\epsilon - \kappa_E)
$$

where $\epsilon$ is the anabolic carbon use efficiency ($1-\epsilon$)
of the uptake is catabolic respiration necessary for synthesizing given 
biomass),
and $\kappa_E$ is the fraction of enzyme turnover (=production) 
that goes into the DOM pool and uptake.

Depending on whether biomass is starving, i.e. negative biosynthesis, cryptic
growth, we have growth respiration. 
Here, growth respiration ($r_G$) and overflow respiration ($r_o$) are again
expressed per $B$. 
<!-- The part that goes to anablic biomass -->
<!-- or enzyme production is denoted by $C_{\operatorname{synBa}}$. -->

$$
\begin{align}
r_G &= \begin{cases}
  (1-\epsilon) \, C_{\operatorname{synB}},  & \text{if } C_{\operatorname{synB}} >
  0\\
  0, & \text{otherwise}
\end{cases} 
\\  
r_O &= C_{\operatorname{synBC}} - C_{\operatorname{synB}}
\end{align}
$$

<!-- C_{\operatorname{synBa}} &= \begin{cases} -->
<!--   \epsilon \, C_{\operatorname{synB}},  & \text{if } C_{\operatorname{synB}} > -->
<!--   0\\ -->
<!--   C_{\operatorname{synB}}, & \text{otherwise} -->
<!-- \end{cases}  -->

$C_{\operatorname{synB}} = C_{\operatorname{synBa}} + r_G$ 
is the carbon flux per $B$ available for biosynthesis 
and associated growth respiration per $B$. 
Its the minimum of the fluxes constrained by element $E \in \{C,N\}$.

$$
\begin{align}
C_{\operatorname{synB}} &= \min_E(C_{\operatorname{synBE}})
\\  
C_{\operatorname{synBC}} &= \operatorname{dec}_L L + \operatorname{dec}_R R -m_E - m
\end{align}
$$

### Transfer of product
Respiration carries the signal of uptake of decomposition 
or if bimass is decreasing a mixture of uptake and 
microbial biomass. 

However when not considering isotopes or fraciotns we can describe respiration  
all leaving the biomass pool.
Hemce, all decomposition fluxes go to DOM and by quasis steady state to $B$. 
Part of the turnover of microbial biomass and turnover of enzymes goes to $R$.

$$
\begin{align}
T_{L \to B} = T_{R \to B} &= 1
\\
T_{B \to R} &= \frac{\epsilon_{Tvr} \tau + (1-\kappa_E) a_E}{\operatorname{out}_B} 
  = \frac{\epsilon_{Tvr} \tau + (1-\kappa_E) a_E}{\tau +m +m_E +r_G +r_O}
\end{align}
$$


## Nitrogen compartment
### State variables
$$
(L_N, R_N, B_N, IN)
$$
In SESAM3 code always $B_N = \beta_B B$ is not explicitly tracked.
But here we report its description for checking the compartmental conditions.

### Inputs
To labile OM pool and to inorganic pool:
$$
\begin{align}
i_{L_N}(t) &= i_L(t) \beta_{iL}
\\
i_I(t) &
\end{align}
$$


### Outfluxes of the pools
Are expressed normalized to the respective pool. Hence they, need to be multiplied by the respiective pool to give a flux.

$$
\begin{align}
\operatorname{out}_{L_N} &= \operatorname{out}_{L}
\\
\operatorname{out}_{R_N} &= \operatorname{out}_{R}
\\
\operatorname{out}_{IN} &= k_{IP}+ lN + i_B 
\\
\operatorname{out}_{B_N} &= \tau  + \operatorname{out}_{B_NEnzR} + 
    \operatorname{out}_{B_NEnzI} +  M_{\operatorname{Imb}} 
\end{align}
$$
where $k_{IP}$ is plant uptake rate, $lN$ is leaching rate, and $i_B$ is 
maximum immobilization rate. 

Net loss of enzyme production going to the $R_N$ pool during
enzyme turnover and to $IN$ during mineralization in DOM uptake:
$$
\begin{align}
\operatorname{out}_{B_NEnzR} &= \operatorname{syn}_{B_NEnz} (1-\kappa_E)
\\
\operatorname{out}_{B_NEnzI} &= \operatorname{syn}_{B_NEnz} \kappa_E (1-\nuN) 
\\
\operatorname{syn}_{B_NEnz} &= a_E \beta_B/\beta_E 
\end{align}
$$
The remaining par is uptake of enzyme turnover from DOM in quasi steady state:
$$
\operatorname{reuptake}_{B_NEnz} = \operatorname{syn}_{B_NEnz} \kappa_E \nuN
= a_E \beta_B/\beta_E \kappa_E \nuN
$$

Although SESAM3 does not model gross immobilizationa and gross mineralization
here we describe the a maxium immobilization flux, $i_B IN$
leaving the $IN$ pool to $B$, and parts of it later return to $IN$ 
as imbalance flux.

The imbalance and synthesis per microbioal biomass N, $B_N$, is

$$
\begin{align}
M_{\operatorname{Imb}} &= N_{\operatorname{synBN}} - (C_{\operatorname{synB}} -r_G)
\\
N_{\operatorname{synBN}} &= u_N - \operatorname{syn}_{B_NEnz}
\\
u_N &= \nuN (k_L l_L L_N  +  k_R l_R R_N 
  + \kappa_E a_E /\beta_E) \beta_B
  + i_B IN/B_N 
\end{align}
$$

The uptake, also, is expressed per microbial biomass N.
The limitation of decomposition fluxes $lN$ and enzyme investment $a_E$
need to be multiplied by $B = \beta_B B_N$ instead of $B_N$. 
Thats why the $\beta_B$ occurs as multiplicator.

The biomass synthesis constraint per microbial Biomass due to N expressed
as proportion of microbial biomass N is the same as proportion of biomass 
syntheis constraint expressed in N per biomass N.
However, because carbon constraints must account for catabolic respiration,
we must devide by $\epsilon$ if constraint is positive.

$$
\begin{align}
C_{\operatorname{synBNa}} &= N_{\operatorname{synBN}} B_N \beta_B /B 
  = N_{\operatorname{synBN}} 
\\
C_{\operatorname{synBN}} &= \begin{cases}
  N_{\operatorname{synBN}} / \epsilon,  & \text{if } N_{\operatorname{synBN}} >
  0\\
  N_{\operatorname{synBN}}, & \text{otherwise}
\end{cases} 
\end{align}  
$$


### Transfer coefficients

Part $1-\nuN$ of the decomposition is mineralized during uptake mineraliztion.
Since always $B_N = B / \beta_B$, it is not explicitly tracked as state 
variable, but part of the model matrix form description.

$$
\begin{align}
T_{L_N \to B_N} &= T_{R_N \to B_N} = \nuN
\\
T_{L_N \to IN} &= T_{R_N \to IN} = 1 - \nuN
\\
T_{B_N \to R_N} &=  
\frac{\epsilon_{\operatorname{Tvr}} \tau + \operatorname{out}_{B_NEnzR}}{\operatorname{out}_{B_N}}
\end{align}
$$

SESAM3 does not compute gross mineralization and gross immobilization, but
only the net flux. 
For convenience, however, we describe the maximum flux from $IN$ to $B$, and
the flux from $B$ to $IN$ as the imbalance between the maximum 
gross immobilization plus organic N uptake and microbial demand.
$$
\begin{align}
T_{IN \to B_N} &= \frac{i_B}{\operatorname{out}_{IN}} = \frac{i_B}{k_{IP}+ lN + i_B}
\\
T_{B_N \to IN} &= \frac{\operatorname{out}_{B_NEnzI} + M_{\operatorname{Imb}} }{\operatorname{out}_{B_N}}
\end{align}
$$

## Community composition
Community composition is not compartmental.
It has no exchange with other pools nor inputs nor outputs 
and only influences the rates of other pools.
It implements a time lag behind a target composition.

$$
\frac{d\alpha}{dt} = (\alpha_{\operatorname{Target}} - \alpha)
  ( \tau + \mid C_{\operatorname{synB}} - r_G \mid) 
$$
With $\alpha_{\operatorname{Target}}$ described in appendix A4.

Note that here, $C_{\operatorname{synB}}$ and $r_G$ are expressed per
microbial biomass, differently from Appendix A in Wutzler 2019.



